# Generated by Django 5.2.4 on 2025-07-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='persona',
            name='oficina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='oficinas.oficina', verbose_name='Oficina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
